version: '3'
services:
  node-app:
    build: ./
    volumes:
    - ./:/app
    env_file: ./.env
    working_dir: /app
    ports:
    - "5000:5000"
    command: ["npm", "start"]
    container_name: funretro