version: '3'
services:
  node-app:
    build: ./
    volumes:
    - ./:/app
    env_file: ./.env
    working_dir: /app
    ports:
    - "5000:5000"
    command: bash -c "cd /app && npm i && gulp && npm run start"
    container_name: funretro